version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: db_club
    depends_on:
      - mysql_db
    networks:
      - backend
    restart: unless-stopped

  mysql_db:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_club
      MYSQL_ROOT_HOST: "%" # Permet les connexions de n'importe quelle origine
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Volume persistant pour les données
      - ./data:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - backend
    # command: --default-authentication-plugin=mysql_native_password  # Pour la compatibilité
    # healthcheck:  # Ajout d'un healthcheck
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  phpmyadmin_db:
    image: phpmyadmin
    container_name: phpmyadmin_db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    restart: always
    depends_on:
      - mysql_db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: # Déclaration du volume
