version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
    - .:/app
    - /app/node_modules
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: my_database
    networks:
      - backend

  mysql:
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_club
    ports:
      - 3306:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d 
    restart: always
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: mysql 
      PMA_PORT: 3306
    restart: always
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge